[package]
name = "panic-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enumset = "1.0.12"
pest = "2.5.6"
pest_ascii_tree = "0.1.0"
pest_derive = "2.5.6"
